# Generated by Django 4.2.5 on 2024-02-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
